development:
  adapter: postgresql
  database: graffito2_development
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: graffito2_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: graffito2_production
  pool: 5
  timeout: 5000

